import { format } from 'date-fns'
import { RouterOutputs } from '~/utils/api'
import ScrambleDisplay from './scramble-display'

type Group = RouterOutputs['group']['getAll'][number]

interface Props {
  groups: Group[]
}

const ScrambleRow: React.FC<{ index: number; group: Group }> = ({
  index,
  group,
}) => (
  <tr>
    <td className="border px-2 py-1 text-center align-top">{index + 1}</td>
    <td className="border px-2 py-1 text-sm">{group.scramble}</td>
    <td className="border px-2 py-1">
      <ScrambleDisplay
        scramble={group.scramble}
        event={group.cubeType?.scrambleMapper ?? ''}
      />
    </td>
  </tr>
)

export default function ScrambleSheetPDF({ groups }: Props) {
  return (
    <div
      id="scramble-sheet"
      className="w-[210mm] h-[297mm] p-[10mm] bg-white font-sans hidden"
    >
      <h1 className="text-2xl font-bold text-center mb-4">
        Scrambles for {format(new Date(), 'yyyy-MM-dd')}
      </h1>
      <h2 className="text-xl font-semibold text-center mb-4">3x3x3 Round 1</h2>

      <table className="w-full border-collapse">
        <thead>
          <tr>
            <th className="border px-2 py-1 w-8">#</th>
            <th className="border px-2 py-1">Scramble</th>
            <th className="border px-2 py-1 w-24">Diagram</th>
          </tr>
        </thead>
        <tbody>
          {groups.slice(0, 5).map((group, index) => (
            <ScrambleRow
              key={`main-group-${index}`}
              index={index}
              group={group}
            />
          ))}
        </tbody>
      </table>

      <h3 className="text-lg font-semibold mt-8 mb-4">Extra Scrambles</h3>
      <table className="w-full border-collapse">
        <tbody>
          {groups.slice(-2).map((group, index) => (
            <ScrambleRow
              key={`extra-group-${index}`}
              index={index}
              group={group}
            />
          ))}
        </tbody>
      </table>

      <div className="text-center text-sm mt-8">
        Generated by TNoodle-WCA-1.2.2
      </div>
      <div className="absolute bottom-[10mm] right-[10mm] text-gray-400 rotate-45 text-4xl font-bold opacity-20">
        MINICK
      </div>
    </div>
  )
}
